{{- if .Values.grafana.enabled -}}
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/common-name: grafana.ops.gcp.zencastr.com
  labels:
    app.kubernetes.io/instance: gke-ops-prometheus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.0.3
    helm.sh/chart: grafana-6.13.5
  name: gke-ops-prometheus-operator-grafana
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.ops.gcp.zencastr.com
    http:
      paths:
      - backend:
          service:
            name: gke-ops-prometheus-operator-grafana
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: blackhole
            port:
              number: 9999
        path: /metrics
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - grafana.ops.gcp.zencastr.com
    secretName: grafana-tls
{{- end -}}    
